# -*- coding: utf-8 -*-
"""audio_memory_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSYmJwFGJtrMalPvCTd50vZV6WRfmtOA
"""

!pip install folium gradio soundfile pydub librosa

import os
import json
import uuid
import folium
import gradio as gr
import soundfile as sf
import librosa
from IPython.display import display

DATA_FILE = "memories.json"
UPLOAD_DIR = "uploads"

os.makedirs(UPLOAD_DIR, exist_ok=True)

# --- db functions ---
def load_memories():
    if not os.path.exists(DATA_FILE):
      return []
    with open(DATA_FILE, "r") as f:
        return json.load(f)

def save_memories(memories):
    with open(DATA_FILE, "w") as f:
        json.dump(memories, f, indent=2)

from re import U
# --- save audio memory ---
def add_memory(title, lat, lon, audio_path):
    memories = load_memories
    memory_id = str(uuid.uuid4())

    new_audio_path = f"{UPLOAD_DIR}/{memory_id}.wav"
    os.rename(audio_path, new_audio_path)

    memory = ({
        "id": memory_id,
        "title": title,
        "lat": lat,
        "lon": lon,
        "audio_path": new_audio_path,
        "transcript": ""
    })

    memories.append(memory)
    save_memories(memories)
    return f"Saved memory: {title}"

# render map of NYC
def render_map():

  memories = load_memories()

  m = folium.Map(location=[40.7128, -73.9352], zoom_start=12)

  for memory in memories:

    popup_html = f"""
    <b>{memory["title"]}</b><br>
    <audio controls>
      <source src="{memory["audio_path"]}" type="audio/wav">
    </audio>
    """

    folium.Marker(
      location=[memory["lat"], memory["lon"]],
      popup=popup_html,
      tooltip=memory["title"]
    ).add_to(m)

  return m

# display map
m = render_map()
m

def upload_memory(title, lat, lon, audio):
  return add_memory(title, float(lat), float(lon), audio)

demo = gr.Interface(
    fn=upload_memory,
    inputs=[
        gr.Textbox(label="Memory Title"),
        gr.Number(label="Latitude"),
        gr.Number(label="Longitude"),
        gr.Audio(type="filepath", label="Record or Upload Audio")
    ],
    outputs="text",
    title="Audio Memory Map",
    description="Upload a memory to a specific place."
)

demo.launch()